name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4]
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.postgresql-test', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    # - name: Install the latest version of ChromeDriver
      # run: php artisan dusk:chrome-driver
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Start Database
      run:
        sudo /etc/init.d/postgresql start
    - name: Create Database
      run: |
        sudo -u postgres psql -c "CREATE USER test WITH PASSWORD 'test'"
        sudo -u postgres psql -c "CREATE DATABASE test OWNER test"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE test to test"
    - name: Database migration
      run: php artisan migrate
     # - name: Run chrome driver Linux in the background
      # run: nohup bash -c './vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &'
    # - name: Run `php artisan serve` in the background to have a local server to use for the tests.
      # run: nohup bash -c 'php artisan serve > /dev/null 2>&1 &'

    # - name: Execute tests (Dusk tests) via Dusk
      # run: php artisan dusk --without-tty --no-interaction
    - name: run unit test
      run: ./vendor/bin/phpunit
